services:
  - type: web
    name: hotllink-backend
    runtime: node
    branch: main
    rootDir: backend-hotllink
    dockerfilePath: ./Dockerfile
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        value: http://localhost:5173
    healthCheckPath: /
